# Setup the kaniko namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: tff-worker@dev-bytetoko.iam.gserviceaccount.com
  name: tff
  namespace: tff