apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tff
namePrefix: jlewi-
labels:
- includeSelectors: true
  pairs:
    app: jlewi-remote
resources:
- statefulset.yaml
images:
- name: executor
  newName: gcr.io/tensorflow-federated/remote-executor-service
  newTag: latest
