apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  ports:
  - name: grpc
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    component: pod
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
spec:
  # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
  # N.B. This is an attempt to ensure that when we update the statefulset we will kick the pod
  # even if there is only one pod.
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  serviceName: worker
  template:
    metadata:
      labels:    
        component: pod
    spec:
      containers:
      - image: executor  
        name: worker
        resources:
          limits:
            cpu: "8"
            memory: 16Gi
            ephemeral-storage:  10Gi
          requests:
            cpu: "4"
            memory: 4Gi
            ephemeral-storage:  10Gi
      serviceAccountName: tff
